### ISSUE TITLE
运行Bug

### ISSUE THREAD

**Issue by bravejpg** [orion-orion/AirPassengerAnalysis#2]
我有一些疑惑，我讲我的运行环境调到了项目的运行环境，但是仍然出现问题，例如这个错误;ImportError: cannot import name 'function_pb2' from 'tensorflow.core.framework' (unknown location)。如果您能给予我一些帮助，不胜感激

**Comment by orion-orion** [comment]
您的tensorflow版本是多少？这个项目用的版本是2.4.1，可能是版本不同导致API变了

**Comment by bravejpg** [comment]
我有一个疑问非常希望能得到您的解答，我在没有把运行环境调整到项目指定的运行环境前，跑出过一些数据，输出了epoch,loss,train acc,test acc,train f1,test f1,train auc,test auc,所以我想知道最后的输出什么样的形式，是带有可视化和数据吗，还是只有数据，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lonelyprince7/AirPassengerAnalysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2)





 
您的tensorflow版本是多少？这个项目用的版本是2.4.1，可能是版本不同导致API变了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bravejpg** [comment]
我想请教一下，我在项目的main.py里发现这么个语句“from sklearn.metrics import make_scoreraa”，make_scoreraa是不是多打了两个a？还是我见识短浅了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lonelyprince7/AirPassengerAnalysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2)





 
您的tensorflow版本是多少？这个项目用的版本是2.4.1，可能是版本不同导致API变了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by orion-orion** [comment]
你好，因为这个比赛没对可视化做具体要求，就没有可视化😂



 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月30日 22:36:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2)




 我有一个疑问非常希望能得到您的解答，我在没有把运行环境调整到项目指定的运行环境前，跑出过一些数据，输出了epoch,loss,train acc,test acc,train f1,test f1,train auc,test auc,所以我想知道最后的输出什么样的形式，是带有可视化和数据吗，还是只有数据，谢谢。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "lonelyprince7/AirPassengerAnalysis"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年10月30日(星期六) 晚上9:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2) 
 
 
 
 
 
   
 您的tensorflow版本是多少？这个项目用的版本是2.4.1，可能是版本不同导致API变了 
   
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bravejpg** [comment]
所以最后就只有epoch,loss,train acc,test acc,train f1,test f1,train auc,test auc这些数据是吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lonelyprince7/AirPassengerAnalysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 晚上10:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2)





 你好，因为这个比赛没对可视化做具体要求，就没有可视化😂 
 
 
 
   
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年10月30日 22:36:21 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2) 
 
 
 
 
  我有一个疑问非常希望能得到您的解答，我在没有把运行环境调整到项目指定的运行环境前，跑出过一些数据，输出了epoch,loss,train acc,test acc,train f1,test f1,train auc,test auc,所以我想知道最后的输出什么样的形式，是带有可视化和数据吗，还是只有数据，谢谢。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "lonelyprince7/AirPassengerAnalysis"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年10月30日(星期六) 晚上9:51  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2)  
   
   
   
   
   
     
  您的tensorflow版本是多少？这个项目用的版本是2.4.1，可能是版本不同导致API变了  
     
  —  
  You are receiving this because you authored the thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by orion-orion** [comment]
打错了，是make_scorer


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月30日 22:53:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2)




 我想请教一下，我在项目的main.py里发现这么个语句“from sklearn.metrics import make_scoreraa”，make_scoreraa是不是多打了两个a？还是我见识短浅了。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "lonelyprince7/AirPassengerAnalysis"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年10月30日(星期六) 晚上9:51 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [lonelyprince7/AirPassengerAnalysis] 运行Bug (Issue #2) 
 
 
 
 
 
   
 您的tensorflow版本是多少？这个项目用的版本是2.4.1，可能是版本不同导致API变了 
   
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by A11URE** [comment]
为什么我运行后显示没有编译model呢

**Comment by orion-orion** [comment]
> 

您好，请检查下您的tensorflow-gpu版本是否满足2.4.1哦~
